#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MAJOR 2
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MINOR 3
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_RELEASE 1


#define NVIDIA_VRWORKS_GRAPHICS_VERSION 2,3,1,0
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_MAJOR_MINOR 2,3
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING "2.3.1.0"
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING_SHORT "2.3.1"
#define NVIDIA_VRWORKS_GRAPHICS_VERSION_STRING_MAJOR_MINOR "2.3"
